/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uts_pbo2;

/**
 *
 * @author ASUS
 */
public class AgendaPribadi extends javax.swing.JFrame {

    /**
     * Creates new form AgendaPribadi
     */
    public AgendaPribadi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarJadwal = new javax.swing.JTextArea();
        seninBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        hapusBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selasaBTN = new javax.swing.JButton();
        rabuBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kamisBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jumatBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sabtuBTN = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        mingguBTN = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jButton3.setText("Ubah");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Agenda Pribadi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Jadwal Kegiatan :");

        daftarJadwal.setColumns(20);
        daftarJadwal.setRows(5);
        jScrollPane1.setViewportView(daftarJadwal);

        seninBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seninBTN.setText("Tambah");
        seninBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seninBTNActionPerformed(evt);
            }
        });

        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        hapusBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hapusBTN.setText("Hapus");
        hapusBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBTNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Senin");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Selasa");

        selasaBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selasaBTN.setText("Tambah");
        selasaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selasaBTNActionPerformed(evt);
            }
        });

        rabuBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rabuBTN.setText("Tambah");
        rabuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabuBTNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Rabu");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Kamis");

        kamisBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kamisBTN.setText("Tambah");
        kamisBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kamisBTNActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Jum'at");

        jumatBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jumatBTN.setText("Tambah");
        jumatBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumatBTNActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Sabtu");

        sabtuBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sabtuBTN.setText("Tambah");
        sabtuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabtuBTNActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Minggu");

        mingguBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mingguBTN.setText("Tambah");
        mingguBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mingguBTNActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("Daftar Jadwal :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(seninBTN))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(selasaBTN)))
                                            .addGap(61, 61, 61)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rabuBTN)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kamisBTN)
                                    .addComponent(jumatBTN)
                                    .addComponent(sabtuBTN))
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hapusBTN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(exitBTN))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mingguBTN)
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seninBTN)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kamisBTN)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mingguBTN)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selasaBTN)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumatBTN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rabuBTN)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sabtuBTN))
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusBTN)
                    .addComponent(exitBTN))
                .addContainerGap(424, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void hapusBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTNActionPerformed
        daftarJadwal.setText("");
    }//GEN-LAST:event_hapusBTNActionPerformed

    private void seninBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seninBTNActionPerformed
        daftarJadwal.setText("""
                             Senin:
                             Pukul 07.00 - 08.00: Sarapan dan Persiapan Pergi Kerja
                             Pukul 08.30 - 12.00: Rapat Tim Proyek X
                             Pukul 12.00 - 13.00: Istirahat dan Makan Siang
                             Pukul 13.00 - 15.00: Bekerja di Proyek Y
                             Pukul 15.30 - 16.30: Kumpul dengan Klien Proyek Z
                             Pukul 17.00 - 18.00: Olahraga di Gym
                             Pukul 19.00 - 20.00: Makan Malam
                             Pukul 20.30 - 21.30: Belajar Bahasa Asing
                             """);
    }//GEN-LAST:event_seninBTNActionPerformed

    private void selasaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selasaBTNActionPerformed
        daftarJadwal.setText("""
                             Selasa:
                             Pukul 06.00 - 07.00: Jogging
                             Pukul 07.30 - 08.30: Mandi dan Sarapan
                             Pukul 09.00 - 12.00: Bekerja dari Rumah
                             Pukul 12.30 - 13.30: Diskusi dengan Rekan Kerja
                             Pukul 14.00 - 16.00: Mengerjakan Laporan Bulanan
                             Pukul 16.30 - 17.30: Pertemuan dengan Mentor
                             Pukul 18.00 - 19.00: Belanja Bulanan
                             Pukul 20.00 - 21.00: Nonton Webinar Pendidikan
                             """);
    }//GEN-LAST:event_selasaBTNActionPerformed

    private void rabuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabuBTNActionPerformed
        daftarJadwal.setText("""
                             Rabu:
                             Pukul 08.00 - 09.00: Konsultasi dengan Penasehat Keuangan
                             Pukul 09.30 - 12.00: Proyek Presentasi untuk Rapat Besar
                             Pukul 12.30 - 13.30: Makan Siang dengan Teman Kerja
                             Pukul 14.00 - 16.00: Evaluasi Kinerja Tim
                             Pukul 16.30 - 17.30: Baca Buku Inspiratif
                             Pukul 18.00 - 19.00: Cooking Class Online
                             Pukul 20.00 - 21.30: Menulis Jurnal Pribadi
                             """);
    }//GEN-LAST:event_rabuBTNActionPerformed

    private void kamisBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kamisBTNActionPerformed
        daftarJadwal.setText("""
                             Kamis:
                             Pukul 07.00 - 08.00: Yoga dan Meditasi
                             Pukul 08.30 - 12.00: Rapat Strategi Proyek Baru
                             Pukul 12.00 - 13.00: Istirahat dan Makan Siang
                             Pukul 13.00 - 15.00: Kerja Pemecahan Masalah Proyek
                             Pukul 15.30 - 16.30: Konsultasi dengan Ahli IT
                             Pukul 17.00 - 18.00: Aktivitas Seni (misalnya, melukis atau bermain musik)
                             Pukul 19.00 - 20.00: Makan Malam dengan Keluarga
                             Pukul 20.30 - 21.30: Pelatihan Keterampilan Baru
                             """);
    }//GEN-LAST:event_kamisBTNActionPerformed

    private void jumatBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumatBTNActionPerformed
        daftarJadwal.setText("""
                             Jum'at:
                             Pukul 06.30 - 07.30: Peregangan dan Pemanasan
                             Pukul 08.00 - 12.00: Fokus Menyelesaikan Tugas Penting
                             Pukul 12.30 - 13.30: Makan Siang Bersama Tim
                             Pukul 14.00 - 16.00: Kegiatan Sosial di Komunitas Lokal
                             Pukul 16.30 - 17.30: Evaluasi Kemajuan Proyek
                             Pukul 18.00 - 19.00: Belajar Musik (misalnya, memainkan instrumen)
                             Pukul 20.00 - 21.30: Menonton Film atau Serial Favorit
                             """);
    }//GEN-LAST:event_jumatBTNActionPerformed

    private void sabtuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabtuBTNActionPerformed
        daftarJadwal.setText("""
                             Sabtu:
                             Pukul 08.00 - 09.00: Sarapan Santai
                             Pukul 09.30 - 12.00: Liburan Singkat atau Aktivitas Rekreasi
                             Pukul 12.30 - 13.30: Makan Siang dengan Teman
                             Pukul 14.00 - 16.00: Bekerja pada Proyek Pribadi
                             Pukul 16.30 - 17.30: Olahraga Luar Ruangan
                             Pukul 18.00 - 19.00: Belajar Keterampilan Kreatif Baru
                             Pukul 20.00 - 21.30: Acara Sosial atau Kumpul dengan Keluarga
                             """);
    }//GEN-LAST:event_sabtuBTNActionPerformed

    private void mingguBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mingguBTNActionPerformed
        daftarJadwal.setText("""
                             Minggu:
                             Pukul 09.00 - 10.00: Kegiatan Keagamaan atau Spiritual
                             Pukul 10.30 - 12.00: Brunch dengan Teman atau Keluarga
                             Pukul 12.30 - 15.00: Jalan-Jalan di Taman atau Alam Terbuka
                             Pukul 15.30 - 17.00: Membaca Buku atau Menulis
                             Pukul 17.30 - 18.30: Persiapan untuk Minggu Depan
                             Pukul 19.00 - 20.00: Makan Malam Ringan
                             Pukul 20.30 - 21.30: Menonton Dokumenter atau Pembelajaran Online
                             """);
    }//GEN-LAST:event_mingguBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaPribadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea daftarJadwal;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton hapusBTN;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jumatBTN;
    private javax.swing.JButton kamisBTN;
    private javax.swing.JButton mingguBTN;
    private javax.swing.JButton rabuBTN;
    private javax.swing.JButton sabtuBTN;
    private javax.swing.JButton selasaBTN;
    private javax.swing.JButton seninBTN;
    // End of variables declaration//GEN-END:variables
}
